In [1]:
import numpy as np

In [2]:
import pandas as pd 

In [3]:
import matplotlib.pyplot as plt 

In [4]:
# importing the dataset 

In [5]:
data = pd.read_csv("Churn_Modelling.csv")
data.shape

(10000, 14)

In [6]:
features = data.iloc[:,3:13].values
features
target = data.iloc[:,13].values
target

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
# before we split the data we will encode and dummy  the categoriel variable 

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
LabelEncoder_feature_1 = LabelEncoder()
features[:,1] = LabelEncoder_feature_1.fit_transform(features[:,1])
LabelEncoder_feature_2 = LabelEncoder()
features[:,2] = LabelEncoder_feature_2.fit_transform(features[:,2])
onehotEncoder = OneHotEncoder(categories=[0])
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   # The column numbers to be transformed (here is [1] but can be [0, 1, 3])
    remainder='passthrough')
features = features[:,1:]
features


array([[0, 0, 42, ..., 1, 1, 101348.88],
       [2, 0, 41, ..., 0, 1, 112542.58],
       [0, 0, 42, ..., 1, 0, 113931.57],
       ...,
       [0, 0, 36, ..., 0, 1, 42085.58],
       [1, 1, 42, ..., 1, 0, 92888.52],
       [0, 0, 28, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
# spliting the data into train set and test train .......

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
features_train,features_test,target_train,target_test = train_test_split(features,target,test_size=0.2,random_state=0)

In [12]:
#featuring scalling 

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc= StandardScaler()

In [15]:
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [26]:
features_test.shape

(2000, 9)

# let make the artificial neural network 

In [20]:
# importing the keras libarries and packages 

In [21]:
import keras 

Using TensorFlow backend.
/home/ahmed/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ahmed/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ahmed/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ahmed/anaconda3/lib/python3.7/site-packages/tensorflo

In [22]:
from keras.models import Sequential
# sequential module to initialize our neural network 
# and the dense module that is required to build the layers 
# of our  NN
from  keras.layers import Dense

In [23]:
# let start by initializing the NN Random weights 

In [24]:
# classifier is the futur nn model we goona build
# as we define it as a sequence of layers 
classifier_nn = Sequential()

In [27]:
import tensorflow as tf      
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
'''
to avoid the error 

'''

# we are able to add the different layer in this NN
# we star with the input layer and the hidden layer 
# the first layer is the input layer 

'''
output the number of noead in the hidden layer
unit the initialise the weights small number close to zero 
activation the activation function in the hiden layyer
'''

classifier_nn.add(Dense(6, kernel_initializer="uniform", activation = 'relu',input_dim=9))


# we create a second hidden layer 
# the number of the noeaud of the second layer is applied 
# as the same of the first the mean (nb ind vari + dep vari / 2 )
classifier_nn.add(Dense(6, kernel_initializer="uniform", activation = 'relu'))

# adding the output layer  the final 
'''
we need only one output dim to one cause we have only one dep var
yes or no if we have more than two categorie we have to change 
the sigmoid funct to soft max  which is applied to dep vari
'''
classifier_nn.add(Dense(1, kernel_initializer="uniform", activation = 'sigmoid'))

# the next step is to compile our neural networks
'''
    optimizer the algorith to use to find the optimal weights
like gradient descent scho.... (caleed adam )
    loss  = the loss function that we need to optimise 
like the error function
    metrixs is a criter that you choose to evalute your model 
and typicly we use the accuracy  it wait a list of matrix
in our case we have only accuracy 

'''
classifier_nn.compile(optimizer="adam",loss="binary_crossentropy",metrics= ["accuracy"])



# the next step is we will choose the number of epoc that is 
# the number of times we training NN 
'''
we will see how our NN in training and how in is improving accuracy at each round of epoc 

'''
# fitting the NN to  the training se 
''' make the connection between NN and training set '''
classifier_nn.fit(features_train,target_train,batch_size= 10,epochs=100)



Epoch 1/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.5297 - accuracy: 0.7958
Epoch 2/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4640 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4434 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4355 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4298 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4210 - accuracy: 0.7952
Epoch 7/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4088 - accuracy: 0.8112
Epoch 8/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4009 - accuracy: 0.8111
Epoch 9/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.3927 - accuracy: 0.8209
Epoch 10/100
8000/8000 [==============================]

# finaly our model is ready 

# making the predictions and evaluation of the model 

In [ ]:
# predictions the test set result 

In [32]:
target_predict = classifier_nn.predict(features_test)
target_predict = (target_predict > 0.5)
target_predict

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [34]:
# making the confusion Matrix 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(target_test,target_predict)
cm

array([[1487,  108],
       [ 180,  225]])

In [36]:
# the accuracy 
(1489+225)/2000
# the recall 
(180+108)/2000

0.144