# DATA PROCESSING 

 * import libraries 

In [1]:
import numpy as np 

In [2]:
import matplotlib.pyplot as plt

In [3]:
import pandas as pd 

In [4]:
data = pd.read_csv("Data.csv")

In [5]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [6]:
features = data.iloc[:,:-1].values
features[:,1:3]
target = data.iloc[:,3].values

In [7]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# taking care of the missing value

In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer = SimpleImputer(missing_values=np.nan,strategy="mean",verbose=0,)


In [10]:
imputer = imputer.fit(features[:,1:3])

In [11]:
features[:,1:3] = imputer.transform(features[:,1:3])
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# encode categoriel data 

In [12]:
# encode the texte to number 

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
labelEncoder_features = LabelEncoder()

In [15]:
features[:,0]= labelEncoder_features.fit_transform(features[:,0])

In [17]:
features

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [18]:
# the problem that even we replaced the string by
#number the equation think that 2 more value than zero
# so the observation are prevaricate

In [19]:
# so we have to prevent the machine by using 
# dummy encoding 

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [21]:
onehotEncoder = OneHotEncoder(categories=[0])
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough')

In [22]:
features = ct.fit_transform(features)

In [23]:
features

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [24]:
# here the machine will recognize the target variable
labelEncoder_target = LabelEncoder()

In [25]:
target= labelEncoder_target.fit_transform(target)

In [26]:
target

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [27]:
# splliting the dataset into the training set and Test test

In [28]:
from sklearn.model_selection import train_test_split 

In [29]:
features_train,featyres_test,target_train,target_test = train_test_split(features,target,test_size= 0.2,random_state= 0)

In [30]:
features_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [31]:
featyres_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [32]:
# feature scalling  make  then in the same scaller

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
sc_features = StandardScaler()

In [35]:
features_train = sc_features.fit_transform(features_train)

In [36]:
featyres_test =sc_features.transform(featyres_test)

In [40]:
# do we need to fit and transform the dummy variable ? 
#the answer it depends on the context cause if we scalle the dummy variable 
# we have chances to lose the information of what is the contry of the observation 

In [41]:
features_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [42]:
featyres_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

In [43]:
'''
the other question is do we need to apply feature scalling 
to  target_train and target_test  the answer is one cause is the \
classification probleme but for regression we need to apply feature scalling to depende vaiable
traget as well as possible 
'''

'\nthe other question is do we need to apply feature scalling \nto  target_train and target_test  the answer is one cause is the classification probleme but for regression we need to apply feature scalling to depende vaiable\ntraget as well as possible \n'